### ISSUE TITLE
CKEditor 5 - change the default install and/or update existing installs

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_core#163] opened 2023-01-30 14:13 UTC
This is to discuss the above and make a call

**Comment by justinepocock** [comment] 2023-04-24 19:01
Currently layout paragraphs (and any modal window) isn't working with CKEditor - it's being resolved for D10 and it looks like it's going to be mostly CSS fixes. I've quickly tested it and it seems to be working well, but content editors will need to use it in anger.

https://www.drupal.org/project/drupal/issues/3328425 

There was concern that linkit was broken in CKeditor but I can confirm this is now resolved 
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/638213/234089962-a9a502f9-d361-48d7-82e9-ad6a779bcd3d.png">

There needs to be some manual work for the styles to show - hopefully this is a simple one liner in the theme.info.yml file 
<img width="786" alt="image" src="https://user-images.githubusercontent.com/638213/234090148-748367ad-0f76-400f-bfb9-ec8d52f838f0.png">

The Wrapping chappy is going to be our friend at H&F to ensure the icons don't get overlapped by the rest of the editor - or hidden behind an obscure 'more' menu. 
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/638213/234090257-dc6786c7-9490-4aa5-a318-b024f1171bc8.png">

Also you can only have one CKEditor version at a time so things like HTML pubs which have their own editor format will need to be converted to 5 too (currently need to test a patch for footnotes to work - I'm sure there's other places and council who have custom filter settings)

When migrating from 4 to 5 it took a fair bit of rejigging the custom things like styles and source editing to be able to get things working. I think that was mostly me doing things in the wrong order, but I think that confirms we might need to be providing documentation alongside migration code.

**Comment by stephen-cox** [comment] 2023-04-26 13:27
@willguv This is the CKEditor 5 discussion

**Comment by justinepocock** [comment] 2023-04-26 13:30
This feels like a blocker for upgrading for https://www.drupal.org/project/drupal/issues/3326261 as you can easily mess up the styles right now. I'm pushing ahead with testing it at H&F because the web team there are awesome but as you can see in the screenshot above the green ticks is greyed out because this doesn't work

**Comment by willguv** [comment] 2023-04-26 14:09
Thanks @stephen-cox

**Comment by keelanfh** [comment] 2023-06-21 13:59
https://github.com/localgovdrupal/localgov_core/issues/181

**Comment by keelanfh** [comment] 2023-07-10 16:41
I’ll close this as the default has now been changed, there are other places to discuss issues and the upgrade path is part of the D10 work.

**Closed as completed by keelanfh** 2023-07-10 16:41 UTC
